# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a78309b1c63d7a3839853ab6d186ffa232c20da0634c7e99bef517da59b2aac412997f4fb59888c4249503b2cf60a452b3b395b6c8fa1c95d0b21b695c794e7d

test:
  secret_key_base: 4432654ce8435db626fbd493d840a09b9a33e04655f1a33aee1c95afb23355d75e8f89076cdb86bae3f1fe19ff1f3a5624ce65d4fea86d26b5681afe74c6aeb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
